# -*- coding: utf-8 -*-
"""Louise Poindexter 20701040

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhvcnTzpJ3v0WYuDPBkeytg-wdeLtSIU
"""

students = [
    ("Aaliyah", 4), ("Ben", 1), ("Camila", 3), ("Diego", 5),
    ("Elena", 2), ("Felix", 0), ("Grace", 3), ("Hector", 4),
    ("Isabel", 1), ("Jamal", 5), ("Keira", 0), ("Luis", 2)
]
algebra = ["Algebra", []]
trigonometry = ["Trigonometry", []]
calculus = ["Calculus", []]
math_courses = (algebra, trigonometry, calculus)

for student in students:
    name = student[0]
    score = student[1]
    if score >= 4:
        calculus[1].append(name)
    elif score >= 2:
        trigonometry[1].append(name)
    else:
        algebra[1].append(name)

print(math_courses)
print()
print(math_courses[0])
print(math_courses[1])
print(math_courses[2])

algebra2 = ["Algebra", []]
trigonometry2 = ["Trigonometry", []]
calculus2 = ["Calculus", []]
math_courses2 = (algebra2,trigonometry2,calculus2)

i = 0
while i < 12:
    name = students[i][0]
    score = students[i][1]
    if score >= 4:
        calculus2[1].append(name)
    elif score >= 2:
        trigonometry2[1].append(name)
    else:
        algebra2[1].append(name)
    i = i + 1

print(math_courses2)

students = []
i = 0
print("--- Enter Student Information ---")
while i < 10:
    name = input("Student name: ")
    score = int(input("Math score: "))
    student_tuple = (name, score)
    students.append(student_tuple)

    i = i + 1
algebra = ["Algebra", []]
trigonometry = ["Trigonometry", []]
calculus = ["Calculus", []]
math_courses = (algebra, trigonometry, calculus)
for student in students:
    student_name = student[0]
    student_score = student[1]

print("Math Placement Report")
print(math_courses[0][0] + ": " + str(math_courses[0][1]))
print(math_courses[1][0] + ": " + str(math_courses[1][1]))
print(math_courses[2][0] + ": " + str(math_courses[2][1]))

