# -*- coding: utf-8 -*-
"""heart_screen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uerDCj_sILUq2KKqDurVelsnSxCAt4K5
"""

import patient_data9 as patient_data
patients = patient_data.get_patients()

print("Patients Matching Screening Rule")
print("--------------------------------")
print(" ")
for patient in patients:
    patient_data.screening_rule(patient)
    patient_data.display_patient(patient)
    print("")