# -*- coding: utf-8 -*-
"""patient_data9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MRs8Knp--JLBpmJsoaIIY20CofRnTEL
"""

patients = [
("Alan Reed", "000-00-0001", 74,
"04/12/1952", 70, 218, "M"),
("Maria Lopez", "000-00-0002", 76,
"09/03/1950", 64, 155, "F"),
("Robert Chen", "000-00-0003", 68,
"01/19/1958", 72, 225, "M"),
("James Hill", "000-00-0004", 82,
"11/28/1943", 69, 210, "M"),
("Susan Patel", "000-00-0005", 72,
"06/14/1954", 65, 205, "F"),
("David King", "000-00-0006", 71,
"02/07/1955", 71, 195, "M"),
("Henry Cole", "000-00-0007", 79,
"08/21/1947", 68, 242, "M"),
("Linda Grant", "000-00-0008", 66,
"12/02/1959", 63, 180, "F")
]

def get_patients():
  """Returns a list of patients."""
  return patients


def screening_rule(patient):
  """Returns a patient if they meet the screening rules."""
  if patient[2] > 70 and patient[5] > 200 and patient[6] == "M":
     return patient

def display_patient(patient):
  if screening_rule(patient):
    """Displays a patient if they meet the screening rules."""
    print(f"""
    Name: {patient[0]}
    SSN: {patient[1]}
    Age: {patient[2]}
    DoB: {patient[3]}
    Height: {patient[4]}
    Weight: {patient[5]}
    Gender: {patient[6]}""")