# -*- coding: utf-8 -*-
"""Louise Poindexter 20701040

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlBzOF_zxNQXVjByfLvYkksFYFm8LpyQ
"""

from math import cos
x = 0.0, 0.5, 1.0, 1.5, 2.0,
2.5, 3.0, 3.5, 4.0, 4.5

print(0.0,cos(0.0))
print(0.5,cos(0.5))
print(1.0,cos(1.0))
print(1.5,cos(1.5))
print(2.0,cos(2.0))
print(2.5,cos(2.5))
print(3.0,cos(3.0))
print(3.5,cos(3.5))
print(4.0,cos(4.0))
print(4.5,cos(4.5))

"""***roughly 1.5***, yes the graph behavived as expected."""

name = input("studentname: ")
cs_grade = input("Computer Science 1 grade: ")
calc_grade = input("Calculus I grade: ")
physics_grade = input("General Physics I grade: ")
english_grade = input("English Composition grade: ")
seminar_grade = input("First-Year Seminar grade: ")

print("\nReport Card")
print(f"Student: {name}")
print(f"{'Computer Science 1':.<30}{cs_grade}")
print(f"{'Calculus I':.<30}{calc_grade}")
print(f"{'General Physics I':.<30}{physics_grade}")
print(f"{'English Composition':.<30}{english_grade}")
print(f"{'First-Year Seminar':.<30}{seminar_grade}")

cs_students = ["Ada Lovelace", "Alan Turing", "Grace Hopper"]
calc_students = ["Katherine Johnson", "Isaac Newton", "Emmy Noether"]
physics_students = ["Marie Curie", "Albert Einstein", "Richard Feynman"]

cs_roster = ["Computer Science 1", cs_students]
calc_roster = ["Calculus I", calc_students]
physics_roster = ["General Physics I", physics_students]

class_rosters = (
    cs_roster,
    calc_roster,
    physics_roster
)

print(class_rosters)