# -*- coding: utf-8 -*-
"""patient_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjH0_MNJGmBnz_PkEIuvUs2g1qT5DI3X
"""

patients = [
("Alan Reed", "000-00-0001", 74, "04/12/1952", 70, 218, "M"),
("Maria Lopez", "000-00-0002", 76,"09/03/1950", 64, 155, "F"),
("Robert Chen", "000-00-0003", 68, "01/19/1958", 72, 225, "M"),
("James Hill", "000-00-0004", 82, "11/28/1943", 69, 210, "M"),
("Susan Patel", "000-00-0005", 72, "06/14/1954", 65, 205, "F"),
("David King", "000-00-0006", 71, "02/07/1955", 71, 195, "M"),
("Henry Cole", "000-00-0007", 79, "08/21/1947", 68, 242, "M"),
("Linda Grant", "000-00-0008", 66, "12/02/1959", 63, 180, "F")]

def get_patients():
  """Returns the list of patients"""
  return patients

def screening_rule(patient):
  """Returns True if the patient is eligible for screening"""
  age = patient[2]
  weight = patient[5]
  gender = patient[6]
  if gender == "M":
    if age > 70:
      if weight > 200:
        return True

def display_patient(patient):
  """Displays the patient information"""
  print("Name: " + str(patient[0]))
  print("SSN: " + str(patient[1]))
  print("Age: " + str(patient[2]))
  print("DOB: " + str(patient[3]))
  print("Height: " + str(patient[4]))
  print("Weight: " + str(patient[5]))
  print("Gender: " + str(patient[6]))

