# -*- coding: utf-8 -*-
"""heart_screen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kb7-GK_COH0QYrxGQuqEVvac0eXOPCKr
"""

import patient_data

patients = patient_data.get_patients()

for patient in patients:
  if patient_data.screening_rule(patient):
    patient_data.display_patient(patient)
    print("")