# -*- coding: utf-8 -*-
"""Louise Poindexter 20701040

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoFnTisANzra8Xp3CMB8-jAPiEt5wZkh
"""

def f(x):
    return (x + 1) / (x - 1)


values = [0, 0.5, 0.9, 1.1, 1.5, 2]

for x in values:
    print(x, f(x))

values.append(0.99)
values.append(1.01)

print("Near the pole:")

for x in values:
    if x == 0.99 or x == 1.01:
        print(x, f(x))

"""Explain why x = 1 is not included in values.
It ends up making a mathmatical equation that cannot exsist. 1+1/1-1= 2/0, therefore undefined.
• Add the values 0.99 and 1.01. What happens to the
magnitude and sign of f(x) near the pole?
As it moves from left to right it gets larger and more positive and vice versa.
"""

def placement(score):
    if score <= 1:
        return "Algebra"
    elif score <= 3:
        return "Trigonometry"
    else:
        return "Calculus"


print(placement(1))
print(placement(3))
print(placement(5))


students = [
    ("Maya", 20681001, 5),
    ("Noah", 20681002, 1),
    ("Olivia", 20681003, 3),
    ("Liam", 20681004, 4),
    ("Sophia", 20681005, 2),
    ("Ethan", 20681006, 0)
]

algebra = ["Algebra", []]
trig = ["Trigonometry", []]
calculus = ["Calculus", []]

math_courses = (algebra, trig, calculus)

for student in students:
    name, student_id, score = student
    course = placement(score)

    for math_course in math_courses:
        if math_course[0] == course:
            math_course[1].append((name, student_id))

print(math_courses)

i = 0
total = 0

while i < len(math_courses):
    total = total + len(math_courses[i][1])
    i = i + 1

print(total)

"""The final print total is six due to that being the total number of students."""