# -*- coding: utf-8 -*-
"""heart_screen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_80e3rpRhheDoe5bgFLHKKRt3LGN1WB
"""

import patient_data

patients = patient_data.get_patients()

print("Patients Matching Screening Rule\n")

for patient in patients:
    if patient_data.screening_rule(patient):
        patient_data.display_patient(patient)
        print("")