# -*- coding: utf-8 -*-
"""course_tools

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J181ELUnZ2tMOivEW3QWoPFc5B5O4XkL
"""

def add_course(courses, course):
    courses.append(course)

def get_time(course):
    return course[5]

def sort_by_time(courses):
    courses.sort(key=get_time)

def display_courses(courses):
 for course in courses:
  print(course[0],
  course[1],
  course[4],
  f"{course[5]:04d}",
  course[2],
  course[3])


def same_room(c1, c2):
    same_building = c1[2] == c2[2]
    same_classroom = c1[3] == c2[3]
    same_time = c1[5] == c2[5]
    shares_day = False
    for day in c1[4]:
        if day in c2[4]:
            shares_day = True
    return same_building and same_classroom and same_time and shares_day

def sort_by_room(courses):
    for i in range(len(courses)):
        for j in range(i + 1, len(courses)):
            if same_room(courses[i], courses[j]):
                print("Conflict:")
                print(courses[i])
                print(courses[j])