# -*- coding: utf-8 -*-
"""Hamilton20672759.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSgqxTGp_Bw62So7luA3mCPEG7LnYep2
"""

import course_tools as tools
course = []


all_course_data = [
    ["CSC", 120, "SLC", 202, "MW", 830],
    ["BSAD", 241, "SLC", 416, "MW", 1200],
    ["MATH", 80, "SLC", 418, "MWF", 1330],
    ["MATH", 141, "SLC", 316, "MTWF", 1000],
    ["BSAD", 213, "HOOVER", 205, "TT", 1500],
    ["CSC", 120, "SLC", 202, "MW", 830],
    ["MATH", 141, "SLC", 316, "MTWF", 1000],
    ["CSC", 220, "SLC", 416, "MWF", 1100],
    ["BSAD", 130, "DEIL", 202, "MWF", 1300]
]


for single_course in all_course_data:
  course.append(single_course)

def get_time(course_item):
    return course_item[5]

course.sort(key=get_time)
for c in course:
    print(c)
# CSC 120 will be first, followed by, 141, 220, 241, 130, 080, and lastly, 213

course.sort(key=lambda course_item: course_item[3])