# -*- coding: utf-8 -*-
"""Homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rEq-i7WY9rtuqF3hAAH_bo_hjwgkFi6
"""

students = [
    ("Aaliyah", 4),
    ("Ben", 1),
    ("Camilla", 3),
    ("Diego", 5),
    ("Elena", 2),
    ("Felix", 0),
    ("Grace", 3),
    ("Hector", 4),
    ("Isabel", 1),
    ("Jamal", 5),
    ("Keira", 0),
    ("Luis", 2)
]

algebra = ["Algebra", []]
trigonometry = ["Trigonometry", []]
calculus = ["Calculus", []]

math_courses = (algebra, trigonometry, calculus)

for student in students:
  name = student[0]
  score = student[1]

  if score >= 4:
    calculus[1].append(name)
  elif score >= 2:
    trigonometry[1].append(name)
  else:
   algebra[1].append(name)

print(math_courses)
print()
print(math_courses[0])
print(math_courses[1])
print(math_courses[2])

students = [
    ("Aaliyah", 4),
    ("Ben", 1),
    ("Camilla", 3),
    ("Diego", 5),
    ("Elena", 2),
    ("Felix", 0),
    ("Grace", 3),
    ("Hector", 4),
    ("Isabel", 1),
    ("Jamal", 5),
    ("Keira", 0),
    ("Luis", 2)
]

algebra2  = ["Algebra", []]
trigonometry2 = ["Trigonometry", []]
calculus2 = ["Calculus", []]

math_courses2 = (algebra2, trigonometry2, calculus2)

i = 0

while i < 12:
  name = students[i][0]
  score = students[i][1]
  if score >= 4:
    calculus2[1].append(name)
  elif score >= 2:
    trigonometry2[1].append(name)
  else:
    algebra2[1].append(name)
  i += 1

print(math_courses2)
print()
print(math_courses2[0])
print(math_courses2[1])
print(math_courses2[2])

students = []

i = 0

while i < 12:
  name = input("Student Name: ")
  score = int(input("Math Score:"))
  students.append((name, score))
  i += 1

algebra3  = ["Algebra", []]
trigonometry3 = ["Trigonometry", []]
calculus3 = ["Calculus", []]

math_courses3 = (algebra3, trigonometry3, calculus3)

for student in students:
  name = student[0]
  score = student[1]
  if score >= 4:
    calculus3[1].append(name)
  elif score >= 2:
    trigonometry3[1].append(name)
  else:
    algebra3[1].append(name)

    print("Math Placement Report")
    print(math_courses[0][0] + ":")
print(math_courses[0][1])

print(math_courses[1][0] + ":")
print(math_courses[1][1])

print(math_courses[2][0] + ":")
print(math_courses[2][1])