# -*- coding: utf-8 -*-
"""heart_screen.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrF3G0ocpmQ0DGzR_bpgq1eQ6Yuf5v5P
"""

import patient_data

patients = patient_data.get_patients()

for patient in patients:
  if patient_data.screening_rule(patient):
    patient_data.display_patient(patient)
    print("")