# -*- coding: utf-8 -*-
"""heart_screen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjarz9dkhZ1TRLZKc8xdrs1FOIgz7J54
"""

import patient_data
patients = patient_data.get_patients()
for patient in patients:
  if patient_data.screening_rule(
patient):
    patient_data.display_patient(
patient)
  print("")