# -*- coding: utf-8 -*-
"""course_tools

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToOke2t7_7ducHSxol0SfCEpFPP1vvNn
"""

def add_course(courses, course):
    courses.append(course)


def get_time(course):
    return course[5]


def sort_by_time(courses):
    courses.sort(key=get_time)


def display_courses(courses):
    for course in courses:
        print(
            course[0],
            course[1],
            course[4],
            f"{course[5]:04d}",
            course[2],
            course[3]
        )


def room_conflict(course1, course2):
    # Same building and room
    same_room = (
        course1[2] == course2[2]
        and course1[3] == course2[3]
    )

    # Same meeting time
    same_time = course1[5] == course2[5]

    # At least one shared meeting day
    shared_day = False
    for day in course1[4]:
        if day in course2[4]:
            shared_day = True
            break

    return same_room and same_time and shared_day