# -*- coding: utf-8 -*-
"""Homework 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6TfER7-mFeDXF3P7U-prgB1wn5hc9P5
"""

def f(x):
  return (x+1)/(x-1)
values = [0, 0.5, 0.9, 0.99, 1.01, 1.1, 1.5, 2]

print("Evaluating original values:")
for x in values:
    print(f"x = {x:<5} f(x) = {f(x):.2f}")

def placement(score):
  if 0 <= score <= 1:
     return "Algebra"
  elif 2 < score <= 3:
     return "Trigonometry"
  elif 3 < score >= 4:
     return "Calculus"
  else:
    return "Invalid Score"

students = [
("Maya", 20681001, 5),
("Noah", 20681002, 1),
("Olivia", 20681003, 3),
("Liam", 20681004, 4),
("Sophia", 20681005, 2),
("Ethan", 20681006, 0)
]

algebra = ["Algebra", []]
trig = ["Trigonometry", []]
calculus = ["Calculus", []]
math_courses = (algebra, trig, calculus)

for student in students:
  name, student_id, score = student
  course = placement(score)

  course_assignment = placement(score)

  if course_assignment == "Algebra":
        algebra[1].append((name, student_id))
  elif course_assignment == "Trigonometry":
        trig[1].append((name, student_id))
  elif course_assignment == "Calculus":
        calculus[1].append((name, student_id))

print("Final Roster Structure (math_courses):")

print(math_courses[0])
print(math_courses[1])
print(math_courses[2])

i = 1
total = 0

while i < len(math_courses):
  total += len(math_courses[i][1])
  i += 1

print(f"Total: {total}")

