# -*- coding: utf-8 -*-
"""Week5BONUS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfDuNEc9Vn6_d5eW60LE2YzC4msVs-k8
"""

import course_tools3 as tools
course = []


all_course_data = [
    ["CSC", 120, "SLC", 202, "MW", 830],
    ["BSAD", 241, "SLC", 416, "MW", 1200],
    ["MATH", 80, "SLC", 418, "MWF", 1330],
    ["MATH", 141, "SLC", 316, "MTWF", 1000],
    ["BSAD", 213, "HOOVER", 205, "TT", 1500],
    ["CSC", 120, "SLC", 202, "MW", 830],
    ["MATH", 141, "SLC", 316, "MTWF", 1000],
    ["CSC", 220, "SLC", 416, "MWF", 1100],
    ["BSAD", 130, "DEIL", 202, "MWF", 1300]
]


for single_course in all_course_data:
  course.append(single_course)

def get_time(course_item):
    return course_item[5]

tools.sort_by_time(course)
tools.display_courses(course)
# CSC 120 will be first, followed by, 141, 220, 241, 130, 080, and lastly, 213

tools.sort_by_room(courses)

